[build]
  CI= "npm run build"
  publish = "dist"
  NODE_ENV = "14.17.0"

[dev]
  command = "npm run build"

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/assets/img/tiny/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/assets/img/small/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=480"
  status = 302

[[redirects]]
  from = "/assets/img/medium/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=768"
  status = 302

[[redirects]]
  from = "/assets/img/large/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=1024"
  status = 302

[[redirects]]
  from = "/assets/img/original/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat"
  status = 302
