[build]
  command = "npm run build"
  publish = "dist"
  NODE_ENV = "14.17.0"

[dev]
  command = "npm run build"

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/assets/img/tiny/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/assets/img/small/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=480"
  status = 302

[[redirects]]
  from = "/assets/img/medium/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=768"
  status = 302

[[redirects]]
  from = "/assets/img/large/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=1024"
  status = 302

[[redirects]]
  from = "/assets/img/original/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat"
  status = 302


[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # to audit a sub path of the build directory
  # route1 audit will use the top level thresholds
  [[plugins.inputs.audits]]
    path = "/en/"

    # you can specify output_path per audit, relative to the path
    output_path = "reports/lighthouse.html"
