[dev]
  command = "npx @11ty/eleventy --serve"
  port = 8888
  targetPort = 8080

[build]
  command = "git lfs pull && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24.10.0"

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://tghb.studio/de/"

  [[plugins.inputs.audits]]
    url = "https://tghb.studio/de/projekte/"

  [[plugins.inputs.audits]]
    url = "https://tghb.studio/de/leistungen/"

  [[plugins.inputs.audits]]
    url = "https://tghb.studio/de/studio/"
