[build]
  command = "npm run build"
  publish = "dist"
  NODE_ENV = "14.17.0"

[dev]
  command = "npm run build"

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/assets/img/tiny/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/assets/img/small/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=700"
  status = 302

[[redirects]]
  from = "/assets/img/medium/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=800"
  status = 302

[[redirects]]
  from = "/assets/img/large/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=1200"
  status = 302

[[redirects]]
  from = "/assets/img/original/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat"
  status = 302
