[[redirects]]
  from = "/img/tiny/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/img/small/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=500"
  status = 302

[[redirects]]
  from = "/img/medium/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=600"
  status = 302

[[redirects]]
  from = "/img/large/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat?nf_resize=fit&w=700"
  status = 302

[[redirects]]
  from = "/img/original/*"
  to = "https://tghb-studio-dev.netlify.app/assets/img/:splat"
  status = 302
